# -*- coding: utf-8 -*-
"""Descriptive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOUJX-XOn2bHStuxafKYeNE_Fjagzcd5
"""



"""Descriptive Analytics
1. Working with DataFram
"""

#Loading CSV file into python as DataFrame
import pandas as pd
ipl_auction_df = pd.read_csv( 'IPL IMB381IPL2013.csv' )

#Check the nature of variable
type(ipl_auction_df)

#Display First 5 entries with headers
ipl_auction_df.head(5)

#finding summary of DataFrame
#See if type is object it is categorical data
ipl_auction_df.info()

#To find meta data of frame
list(ipl_auction_df)

"""Slicing and Indexing a dataframe"""

#1. By ROWS
#First five entries
ipl_auction_df[0:5]

#Last five entries
ipl_auction_df[-5:]

#Slicing By Colunm
ipl_auction_df['PLAYER NAME'][0:5]

#Slincing only 2 colunm 5 entries
ipl_auction_df[['PLAYER NAME', 'COUNTRY']][0:5]

#Sorting dataframe by column values
ipl_auction_df[['PLAYER NAME','SOLD PRICE']].sort_values('SOLD PRICE')[0:5]

#Creating New Colunm
#Which player got the maximum premium on the base price?
ipl_auction_df['premium'] = ipl_auction_df['SOLD PRICE'] - ipl_auction_df['BASE PRICE']

ipl_auction_df[['PLAYER NAME', 'BASE PRICE', 'SOLD PRICE', 'premium']][0:5]

ipl_auction_df[['PLAYER NAME',
                'BASE PRICE',
                'SOLD PRICE', 'premium']].sort_values('premium',
                                                      ascending = False)[0:5]

"""Grouping and Aggregating

"""

soldprice_by_age = ipl_auction_df.groupby('AGE')['SOLD PRICE'].mean().reset_index()
soldprice_by_age

