# -*- coding: utf-8 -*-
"""Sess5&6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqRdE2lrsecT76-qZrLHVYvDxBWHNFQ7
"""

import numpy as np
import pandas as pd

# Generate sample data
np.random.seed(0)#Configuration for random number
data = pd.DataFrame(np.random.randn(100, 2), columns=['X', 'Y'])#Create a
#two features data, here naming X and Y of size 100 samples

data.head(5)# display the geneted  random data

# Calculate covariance matrix
cov_matrix = np.cov(data['X'], data['Y'])

cov_matrix

# Extract covariance
covariance = cov_matrix[0, 1]# b and c element represent covariance
covariance

# Calculate correlation matrix
cor_matrix = np.corrcoef(data['X'], data['Y'])
cor_matrix

# Extract correlation coefficient
correlation = cor_matrix[0, 1]
correlation



# @title
import matplotlib.pyplot as plt
import seaborn as sns

def create_box_plot(data):
    plt.figure(figsize=(8, 6))
    sns.boxplot(data=data)
    plt.title('Box Plot')
    plt.xlabel('Data')
    plt.ylabel('Values')
    plt.show()

# Example data
data = {
    'Group A': [-1, 12, 15, 18, 20, 22],#add -1 and see outlier
    'Group B': [11, 14, 17, 20, 23, 26],
    'Group C': [8, 10, 12, 14, 16, 18]
}

create_box_plot(data)